# -*- coding: utf-8 -*-
"""exp5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AHGlyqKvEEVyiNIiplSP9NODo0gAdv5V
"""

import pandas as pd
import numpy as np
from scipy.stats import zscore
data = {
    "Student": ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"],
    "Marks": [50, 55, 60, 62, 65, 68, 70, 72, 75, 150]
}
df = pd.DataFrame(data)
print(df)

Q1 = df["Marks"].quantile(0.25)
print(Q1)
Q3 = df["Marks"].quantile(0.75)
print(Q3)

IQR = Q3 - Q1
print(IQR)

lower = Q1 - 1.5 * IQR
print(lower)
upper = Q3 + 1.5 * IQR
print(upper)

outliers = df[(df["Marks"] < lower) | (df["Marks"] > upper)]
print(outliers)

df["Marks_Treated"] = np.where(df["Marks"] < lower, lower, df["Marks"])
df["Marks_Treated"] = np.where(df["Marks_Treated"] > upper, upper, df["Marks_Treated"])

print(df)

df_capped = df.copy()
df["Marks_Treated"] = df["Marks"].clip(lower, upper)

print("\nAfter Capping:")
print(df)

data={
    "students" : ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J",
            "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T"],

"marks" : [50, 52, 54, 55, 56, 58, 60, 61, 62, 63,
         64, 65, 66, 68, 70, 71, 72, 73, 75, 200]
}
df = pd.DataFrame(data)
print(df)
df["Z_Score"] = zscore(df["marks"])

print(df)

outliers = df[abs(df["Z_Score"]) > 3]
print("\n outliers using z score:")
print(outliers)

mean = df["marks"].mean()
sd = df["marks"].std()

lower = mean - 3 * sd
upper = mean + 3 * sd
print("Mean:", mean)
print("Standard Deviation:", sd)
print("Lower Limit:", lower)
print("Upper Limit:", upper)
print(df)

z = (df["marks"] - mean) / sd

df["marks_treated"] = df["marks"].clip(lower, upper)
print(df[["students", "marks", "marks_treated"]])